// Author: fei 2020-08-20
// Auto generated by IPDOC
  #include "common.h"
  #ifdef USE_BANKING
  #pragma codeseg BANK1
  #pragma constseg BANK1
  #endif
  void pll_amp_ts_cont(void) BANKING_CTRL {
    reg_PLL_AMP_TS_TOP_CONT_START_LANE = 0;
    reg_PLL_TS_LCVCOCAL_BUF_EN_LANE = 0;
    reg_PLL_AMP_TS_TOP_CONT_START_LANE = 0;
  }
