// Author: mxlin 2020-08-17
// Auto generated by IPDOC
  #include "common.h"
  #ifdef USE_BANKING
  #pragma codeseg BANK1
  #pragma constseg BANK1
  #endif
  void rx_clk_cont(void) BANKING_CTRL {
    reg_RX_CLK_TOP_CONT_START_LANE = 0;
    reg_DLL_REF_FILT_BW_LANE = 0;
    reg_DLL_HI_BW_LANE = 0;
    reg_RX_DLL_CAL_SAMPLE_PULSE_DIV_LANE_7_0 = 0X22;
    reg_RX_DLL_CAL_AUTO_ZERO_CLK_H_2M_PULSE_CNT_LANE_2_0 = 0X5;
    reg_RX_EOM_DLL_CAL_SAMPLE_PULSE_DIV_LANE_7_0 = 0X22;
    reg_RX_EOM_DLL_CAL_AUTO_ZERO_CLK_H_2M_PULSE_CNT_LANE_2_0 = 0X5;
    reg_RX_ALIGN90_CAL_SETTING_LANE_7_0 = 0X40;
    reg_RX_ALIGN90_CAL_SETTING_LANE_12_8 = 0;
    reg_RX_EOM_PI_CAL_SETTING_LANE_7_0 = 0X40;
    reg_RX_EOM_PI_CAL_SETTING_LANE_12_8 = 0;
    if(reg_PIN_PHY_MODE_RD_2_0 == 3){
      reg_RX_E2C_DCC_CAL_BYPASS_EN_LANE = 0;
      reg_RX_DLL_CAL_BYPASS_EN_LANE = 0;
      reg_RX_PI_DCC_CAL_BYPASS_EN_LANE = 0;
      reg_RX_ALIGN90_CAL_BYPASS_EN_LANE = 0;
      reg_RX_DATA_DCC_CAL_BYPASS_EN_LANE = 0;
      reg_RX_EDGE_DCC_CAL_BYPASS_EN_LANE = 0;
      reg_RX_E2C_DCC_CAL_SINGLE_EN_LANE = 0;
      reg_RX_DLL_CAL_SINGLE_EN_LANE = 0;
      reg_RX_PI_DCC_CAL_SINGLE_EN_LANE = 0;
      reg_RX_ALIGN90_CAL_SINGLE_EN_LANE = 0;
      reg_RX_DATA_DCC_CAL_SINGLE_EN_LANE = 0;
      reg_RX_EDGE_DCC_CAL_SINGLE_EN_LANE = 0;
      reg_RX_CLK_TOP_START_LANE = 0;
      reg_RX_CLK_TOP_START_LANE = 1;
      delay(Tus);
      while(reg_RX_CLK_TOP_DONE_LANE == 0){
      }
      reg_RX_CLK_TOP_START_LANE = 0;
      reg_RX_E2C_DCC_CAL_SINGLE_EN_LANE = 1;
      reg_RX_DLL_CAL_SINGLE_EN_LANE = 1;
      reg_RX_PI_DCC_CAL_SINGLE_EN_LANE = 1;
      reg_RX_ALIGN90_CAL_SINGLE_EN_LANE = 1;
      reg_RX_DATA_DCC_CAL_SINGLE_EN_LANE = 1;
      reg_RX_EDGE_DCC_CAL_SINGLE_EN_LANE = 1;
    }
    if(reg_RXSPEED_DIV_LANE_2_0&0X03 != 0){
      reg_RX_ALIGN90_CAL_BYPASS_EN_LANE = 1;
      reg_RX_EDGE_DCC_CAL_BYPASS_EN_LANE = 1;
    }
    else{
      reg_RX_ALIGN90_CAL_BYPASS_EN_LANE = 0;
      reg_RX_EDGE_DCC_CAL_BYPASS_EN_LANE = 0;
    }
    reg_RX_CLK_TOP_CONT_START_LANE = 1;
  }
