// Author: fei 2020-08-25
// Auto generated by IPDOC
  #include "common.h"
  #ifdef USE_BANKING
  #pragma codeseg BANK1
  #pragma constseg BANK1
  #endif
  void pll_amp_ts(void) BANKING_CTRL {
    reg_PLL_AMP_TS_TOP_START_LANE = 0;
    reg_PLL_AMP_TS_TOP_START_LANE = 1;
    delay(Tus);
    while(reg_PLL_AMP_TS_TOP_DONE_LANE == 0){
    }
    reg_PLL_AMP_TS_TOP_START_LANE = 0;
    if(reg_PLL_TS_AMP_CAL_TIMEOUT_RD_LANE == 1){
      lnx_TX_PLL_AMP_CAL_PASS_LANE = 0;
    }
    else{
      lnx_TX_PLL_AMP_CAL_PASS_LANE = 1;
    }
    reg_PLL_TS_AMP_CAL_RESULT_EXT_LANE_7_0 = reg_PLL_TS_AMP_CAL_RESULT_RD_LANE_7_0;
  }
