// Author: mxlin 2020-08-12
// Auto generated by IPDOC
  #include "common.h"
  #ifdef USE_BANKING
  #pragma codeseg BANK1
  #pragma constseg BANK1
  #endif
  void rx_imp(void) BANKING_CTRL {
    reg_RXIMPCAL_EN_LANE = 1;
    reg_RX_IMP_TOP_START = 0;
    reg_RX_IMP_TOP_START = 1;
    delay(Tus);
    while(reg_RX_IMP_TOP_DONE == 0){
    }
    reg_RX_IMP_TOP_START = 0;
    if(reg_RX_IMP_CAL_TIMEOUT_RD == 0){
      lnx_RXIMP_CAL_PASS_LANE = 1;
    }
    else{
      lnx_RXIMP_CAL_PASS_LANE = 0;
    }
    reg_IMPCAL_RX_LANE_4_0 = reg_RX_IMP_CAL_RESULT_RD_4_0;
    reg_RXIMPCAL_EN_LANE = 0;
  }
