//speed table address offset

//xdat cmn
//lc pll speed table address offset
#define spdoft_pll_reg_sel                              0
#define spdoft_pll_rate_sel                             1
#define spdoft_fbdiv                                    2
#define spdoft_fbdiv_cal                                4
#define spdoft_refdiv                                   6
#define spdoft_vind_band_sel                            7
#define spdoft_div_1g                                   8
#define spdoft_div_1g_fbck                              10
#define spdoft_pll_icp                                  12
#define spdoft_pll_lpfr                                 13
#define spdoft_pll_lpfc                                 14
#define spdoft_init_txfoffs                             15
#define spdoft_speed_thresh                             17
#define spdoft_lccap_usb                                19
#define spdoft_ssc_acc_factor                           20
#define spdoft_ssc_step_125ppm                          21
#define spdoft_ssc_m                                    22

//phy_mode_cmn
#define spdoft_use_ring_refclk_250m                     0
#define caloft_lcvco_dac_lsb_rate0                      1
#define caloft_lcvco_dac_lsb_rate1                      2
#define caloft_lcvco_dac_lsb_cont_rate1                 3
#define caloft_lcvco_dac_msb_rate0                      4
#define caloft_lcvco_dac_msb_rate1                      5
#define caloft_lcvco_dac_msb_cont_rate0                 6
#define caloft_lcvco_dac_msb_cont_rate1                 7
#define caloft_lccap_lsb_rate0                          8
#define caloft_lccap_lsb_rate1                          9
#define caloft_lccap_msb_rate0                          10
#define caloft_lccap_msb_rate1                          11
#define caloft_plldcc_cnt_rate0                         12
#define caloft_plldcc_cnt_rate1                         13
#define caloft_plldcc_cnt_cont_rate0                    14
#define caloft_plldcc_cnt_cont_rate1                    15
#define caloft_pll_speed_ring_rate0                     16
#define caloft_pll_speed_ring_rate1                     17
#define caloft_pll_speed_ring_cont_rate0                18
#define caloft_pll_speed_ring_cont_rate1                19
#define caloft_pll_sllp_dac_coarse_ring_rate0           20
#define caloft_pll_sllp_dac_coarse_ring_rate1           21
#define caloft_pll_sllp_dac_coarse_ring_cont_rate0      22
#define caloft_pll_sllp_dac_coarse_ring_cont_rate1      23
#define caloft_sllp_dac_fine_ring_rate0                 24
#define caloft_sllp_dac_fine_ring_rate1                 26
#define caloft_sllp_dac_fine_ring_cont_rate0            28
#define caloft_sllp_dac_fine_ring_cont_rate1            30

//speed_tx
#define spdoft_pll_rate_sel_tx                          0
#define spdoft_tx_vddcal_rate_en_lane                   1
#define spdoft_tx_speeddiv_lane                         2
#define spdoft_txreg_speedtrk_clk_lane                  3
#define spdoft_txreg_speedtrk_data_lane                 4
#define spdoft_tx_pam2_en_lane                          5
#define spdoft_tx_halfrate_en_lane                      6
#define spdoft_tx_train_pat_sel_lane                    7

//speed_rx
#define spdoft_pll_rate_sel_rx                          8
#define spdoft_rx_vddcal_rate_en_lane                   9
#define spdoft_rx_speed_div_lane                        10
#define spdoft_dtl_clk_speedup_lane                     11
#define spdoft_rxintpi_lane                             12
#define spdoft_intpr_lane                               13
#define spdoft_dll_freq_sel_lane                        14
#define spdoft_eom_dll_freq_sel_lane                    15
#define spdoft_rxreg_speedtrk_data_lane                 16
#define spdoft_rxreg_speedtrk_clk_lane                  17
#define spdoft_rxreg_speedtrk_clk_half_lane             18
#define spdoft_selmufi_lane                             19
#define spdoft_selmuff_lane                             20
#define spdoft_selmupi_lane                             21
#define spdoft_selmupf_lane                             22
#define spdoft_dtl_clk_mode_lane                        23
#define spdoft_rx_foffset_extra_m_lane                  24
#define spdoft_init_rxfoffs_lane                        26
#define spdoft_pu_smplr_d_p2_lane                       28
#define spdoft_pu_smplr_s_p2_lane                       29
#define spdoft_pu_smplr_d_p4_lane                       30
#define spdoft_pu_smplr_s_p4_lane                       31
#define spdoft_path_disable_edge_p2p4_lane              32
#define spdoft_path_disable_edge_p1p3_lane              33
#define spdoft_pu_smplr_d_p1_lane                       34
#define spdoft_pu_smplr_s_p1_lane                       35
#define spdoft_pu_smplr_d_p3_lane                       36
#define spdoft_pu_smplr_s_p3_lane                       37
#define spdoft_path_disable_d_p1p3_lane                 38
#define spdoft_path_disable_s_p1p3_lane                 39
#define spdoft_rxclk_25m_ctrl_lane                      40
#define spdoft_rxclk_25m_div1p5_en_lane                 41
#define spdoft_rxclk_25m_div_lane                       42
#define spdoft_rxclk_25m_fix_div_en_lane                43
#define spdoft_ctle_low_speed_sel_lane                  44
#define spdoft_ctle_bypass1_en_lane                     45
#define spdoft_ctle_bypass2_en_lane                     46
#define spdoft_ctle_current1_sel_lane                   47
#define spdoft_ctle_rl1_sel_lane                        48
#define spdoft_ctle_rf_ctrl_lane                        49
#define spdoft_ctle_rl1_tia_sel_lane                    50
#define spdoft_ctle_current1_tia_sel_lane               51
#define spdoft_ctle_rl2_sel_g_p2_lane                   52
#define spdoft_ctle_current2_sel_g_p2_lane              53
#define spdoft_ctle_rl2_sel_g_p4_lane                   54
#define spdoft_ctle_current2_sel_g_p4_lane              55
#define spdoft_dfe_cur_sel_g_lane                       56
#define spdoft_reg_dfe_rate_mode_lane                   57
#define spdoft_reg_dfe_dis_lane                         58
#define spdoft_reg_dfe_tap_settle_scale_lane            59
#define spdoft_rxdll_temp_a_lane                        60
#define spdoft_rxdll_temp_b_lane                        61
#define spdoft_dfe_pam2_mode_lane                       62
#define spdoft_rx_pam2_en_lane                          63
#define spdoft_rx_halfrate_en_lane                      64

//phy_mode_lane
#define caloft_pll_amp_result_lane                      0
#define caloft_plldcc_result_lane                       1
#define caloft_tx_align90_result_msb_lane               2
#define caloft_tx_align90_result_lsb_lane               3
#define caloft_txdcc1_result_lane                       4
#define caloft_txdcc2_result_lane                       5
#define caloft_dll_gm_result_lane                       6
#define caloft_eom_dll_gm_result_lane                   7
#define caloft_dll_vdda_result_lane                     8
#define caloft_eom_dll_vdda_result_lane                 9
#define caloft_dll_dcc_result_lane                      10
#define caloft_tx_dcc1_result_lane                      11
#define caloft_tx_dcc2_result_lane                      12
#define caloft_tx_dcc3_result_msb_lane                  13
#define caloft_tx_dcc3_result_lsb_lane                  14
#define caloft_tx_dcc4_result_msb_lane                  15
#define caloft_tx_dcc4_result_lsb_lane                  16
#define caloft_tx_imp_n_result_lane                     17
#define caloft_tx_imp_p_result_lane                     18
#define caloft_rx_eom_dcc_result_lane                   19
#define caloft_rx_eom_pi_result_lane                    20
#define caloft_rx_eom_align90_result_msb_lane           21
#define caloft_rx_eom_align90_result_lsb_lane           22
#define caloft_rx_align90_dd_result_msb_lane            23
#define caloft_rx_align90_dd_result_lsb_lane            24
#define caloft_rx_align90_de_result_msb_lane            25
#define caloft_rx_align90_de_result_lsb_lane            26
#define caloft_rx_align90_ee_result_msb_lane            27
#define caloft_rx_align90_ee_result_lsb_lane            28
#define caloft_rx_dcc1_result_msb_lane                  29
#define caloft_rx_dcc1_result_lsb_lane                  30
#define caloft_rx_dcc2_result_msb_lane                  31
#define caloft_rx_dcc2_result_lsb_lane                  32
#define caloft_rx_dcc3_result_msb_lane                  33
#define caloft_rx_dcc3_result_lsb_lane                  34
#define caloft_rx_dcc4_result_msb_lane                  35
#define caloft_rx_dcc4_result_lsb_lane                  36
#define caloft_rx_dcc5_result_lane                      37
#define caloft_rx_imp_result_lane                       38
#define caloft_sq_result_lane                           39
#define caloft_smplr_d_top_p1_result_lane               40
#define caloft_smplr_d_mid_p1_result_lane               41
#define caloft_smplr_d_bot_p1_result_lane               42
#define caloft_smplr_d_top_p3_result_lane               43
#define caloft_smplr_d_mid_p3_result_lane               44
#define caloft_smplr_d_bot_p3_result_lane               45
#define caloft_smplr_s_top_p1_result_lane               46
#define caloft_smplr_s_mid_p1_result_lane               47
#define caloft_smplr_s_bot_p1_result_lane               48
#define caloft_smplr_s_top_p3_result_lane               49
#define caloft_smplr_s_mid_p3_result_lane               50
#define caloft_smplr_s_bot_p3_result_lane               51
#define caloft_smplr_edge_p1_result_pn_sign_lane        52
#define caloft_smplr_edge_p1_result_p_sign_lane         53
#define caloft_smplr_edge_p1_result_n_sign_lane         54
#define caloft_smplr_edge_p3_result_pn_sign_lane        55
#define caloft_smplr_edge_p3_result_p_sign_lane         56
#define caloft_smplr_edge_p3_result_n_sign_lane         57
#define caloft_smplr_d_top_p2_result_lane               58
#define caloft_smplr_d_mid_p2_result_lane               59
#define caloft_smplr_d_bot_p2_result_lane               60
#define caloft_smplr_d_top_p4_result_lane               61
#define caloft_smplr_d_mid_p4_result_lane               62
#define caloft_smplr_d_bot_p4_result_lane               63
#define caloft_smplr_s_top_p2_result_lane               64
#define caloft_smplr_s_mid_p2_result_lane               65
#define caloft_smplr_s_bot_p2_result_lane               66
#define caloft_smplr_s_top_p4_result_lane               67
#define caloft_smplr_s_mid_p4_result_lane               68
#define caloft_smplr_s_bot_p4_result_lane               69
#define caloft_smplr_edge_p2_result_pn_sign_lane        70
#define caloft_smplr_edge_p2_result_p_sign_lane         71
#define caloft_smplr_edge_p2_result_n_sign_lane         72
#define caloft_smplr_edge_p4_result_pn_sign_lane        73
#define caloft_smplr_edge_p4_result_p_sign_lane         74
#define caloft_smplr_edge_p4_result_n_sign_lane         75

//size should be %4 = 0
#define lc_size 32
#define cal_cmn_size 32
#define gen_size 68
#define cal_lane_size 76

#define lc_speed_size 24
#define tx_speed_size 8
#define gen_speed_size 65

#define PHY_MODE_CMN_BASE   0x7000
#define PHY_MODE_LANE_BASE   0x6c84
