// Author: mxlin 2020-08-17
// Auto generated by IPDOC
  #include "common.h"
  #ifdef USE_BANKING
  #pragma codeseg BANK1
  #pragma constseg BANK1
  #endif
  void rx_sq_thr(void) BANKING_CTRL {
    uint8_t VAR_SQ_THRESH_CAL_PASS1;
    uint8_t VAR_RESULT_TEMP1;
    int8_t VAR_THR1;
    uint8_t VAR_SQ_THRESH_CAL_PASS2;
    uint8_t VAR_RESULT_TEMP2;
    int8_t VAR_THR2;
    int8_t VAR_AVG_THR12;
    uint8_t VAR_THRES_CAL_RESULT;
    reg_SQ_CAL_EN_LANE = 1;
    reg_SQ_OFFSET_CAL_EN_LANE = 0;
    reg_SQ_THRESH_CAL_EN_LANE = 1;
    reg_SQ_CAL_RESULT_EXT_LANE_5_0 = 0X20;
    reg_SQ_OFFSETCAL_SEL_LANE_1_0 = 3;
    reg_SQ_REFTHR_LANE_4_0 = 0X07;
    reg_SQ_OFFSETCAL_SEL_LANE_1_0 = 3;
    reg_RX_SQ_TOP_START_LANE = 0;
    reg_RX_SQ_TOP_START_LANE = 1;
    delay(Tus);
    while(reg_RX_SQ_TOP_DONE_LANE == 0){
    }
    reg_RX_SQ_TOP_START_LANE = 0;
    if(reg_SQ_CAL_TIMEOUT_RD_LANE == 1){
      VAR_SQ_THRESH_CAL_PASS1 = 0;
    }
    else{
      VAR_SQ_THRESH_CAL_PASS1 = 1;
    }
    VAR_RESULT_TEMP1 = reg_SQ_CAL_RESULT_RD_LANE_5_0;
    if(VAR_RESULT_TEMP1 & 0X20 == 0){
      VAR_THR1 = 1;
      VAR_THR1 = (VAR_RESULT_TEMP1 & 0X1F)*(-1);
    }
    else{
      VAR_THR1 = VAR_RESULT_TEMP1 & 0X1F;
    }
    reg_SQ_REFTHR_LANE_4_0 = 0X17;
    reg_RX_SQ_TOP_START_LANE = 0;
    reg_RX_SQ_TOP_START_LANE = 1;
    delay(Tus);
    while(reg_RX_SQ_TOP_DONE_LANE == 0){
    }
    reg_RX_SQ_TOP_START_LANE = 0;
    if(reg_SQ_CAL_TIMEOUT_RD_LANE == 1){
      VAR_SQ_THRESH_CAL_PASS2 = 0;
    }
    else{
      VAR_SQ_THRESH_CAL_PASS2 = 1;
    }
    VAR_RESULT_TEMP2 = reg_SQ_CAL_RESULT_RD_LANE_5_0;
    if(VAR_RESULT_TEMP2 & 0X20 == 0){
      VAR_THR2 = 1;
      VAR_THR2 = (VAR_RESULT_TEMP2 & 0X1F)*(-1);
    }
    else{
      VAR_THR2 = VAR_RESULT_TEMP2 & 0X1F;
    }
    if(VAR_SQ_THRESH_CAL_PASS2 && VAR_SQ_THRESH_CAL_PASS1 == 1){
      lnx_SQ_THRESH_CAL_PASS_LANE = 1;
    }
    else{
      lnx_SQ_THRESH_CAL_PASS_LANE = 0;
    }
    VAR_AVG_THR12 = 1;
    VAR_AVG_THR12 = (VAR_THR1+VAR_THR2)/2;
    if(VAR_AVG_THR12 > 0){
      VAR_THRES_CAL_RESULT = (VAR_AVG_THR12 & 0X1F) | 0X20;
    }
    else{
      VAR_THRES_CAL_RESULT = ((-1)*VAR_AVG_THR12) & 0X1F;
    }
    reg_SQ_CAL_RESULT_EXT_LANE_5_0 = VAR_THRES_CAL_RESULT;
    reg_SQ_CAL_INDV_EXT_EN_LANE = 1;
    reg_SQ_CAL_EN_LANE = 0;
    reg_SQ_THRESH_CAL_EN_LANE = 0;
  }
