// Author: mxlin 2020-09-01
// Auto generated by IPDOC
  #include "common.h"
  #ifdef USE_BANKING
  #pragma codeseg BANK1
  #pragma constseg BANK1
  #endif
  void rx_sq_ofst(void) BANKING_CTRL {
    uint8_t VAR_SQ_OFST_CAL_PASS1;
    int8_t VAR_OFST1;
    int8_t VAR_OFST1_MINUS;
    uint8_t VAR_SQ_OFST_CAL_PASS2;
    int8_t VAR_OFST2;
    int8_t VAR_OFST2_MINUS;
    reg_SQ_CAL_EN_LANE = 1;
    reg_SQ_OFFSET_CAL_EN_LANE = 1;
    reg_SQ_THRESH_CAL_EN_LANE = 0;
    reg_SQ_CAL_RESULT_EXT_LANE_5_0 = 0X20;
    reg_SQ_OFFSET_LANE_4_0 = 0X10;
    reg_SQ_OFFSETCAL_SEL_LANE_1_0 = 1;
    reg_RX_SQ_TOP_START_LANE = 0;
    reg_RX_SQ_TOP_START_LANE = 1;
    delay(Tus);
    while(reg_RX_SQ_TOP_DONE_LANE == 0){
    }
    reg_RX_SQ_TOP_START_LANE = 0;
    if(reg_SQ_CAL_TIMEOUT_RD_LANE == 1){
      VAR_SQ_OFST_CAL_PASS1 = 0;
    }
    else{
      VAR_SQ_OFST_CAL_PASS1 = 1;
    }
    VAR_OFST1 = 1;
    VAR_OFST1 = reg_SQ_CAL_RESULT_RD_LANE_5_0 & 0X1F;
    if(reg_SQ_CAL_RESULT_RD_LANE_5_0&0X20 == 0){
      VAR_OFST1_MINUS = 1;
      VAR_OFST1_MINUS = VAR_OFST1*(-1);
      VAR_OFST1 = VAR_OFST1_MINUS;
    }
    reg_SQ_OFFSETCAL_SEL_LANE_1_0 = 2;
    reg_RX_SQ_TOP_START_LANE = 0;
    reg_RX_SQ_TOP_START_LANE = 1;
    delay(Tus);
    while(reg_RX_SQ_TOP_DONE_LANE == 0){
    }
    reg_RX_SQ_TOP_START_LANE = 0;
    if(reg_SQ_CAL_TIMEOUT_RD_LANE == 1){
      VAR_SQ_OFST_CAL_PASS2 = 0;
    }
    else{
      VAR_SQ_OFST_CAL_PASS2 = 1;
    }
    VAR_OFST2 = 1;
    VAR_OFST2 = reg_SQ_CAL_RESULT_RD_LANE_5_0 & 0X1F;
    if(reg_SQ_CAL_RESULT_RD_LANE_5_0&0X20 == 0){
      VAR_OFST2_MINUS = 1;
      VAR_OFST2_MINUS = VAR_OFST2*(-1);
      VAR_OFST2 = VAR_OFST2_MINUS;
    }
    if(VAR_SQ_OFST_CAL_PASS2 && VAR_SQ_OFST_CAL_PASS1 == 1){
      lnx_SQ_OFST_CAL_PASS_LANE = 1;
    }
    else{
      lnx_SQ_OFST_CAL_PASS_LANE = 0;
    }
    if(VAR_OFST1 >= VAR_OFST2){
      reg_SQ_OFFSET_LANE_4_0 = ((VAR_OFST1 - VAR_OFST2) & 0XF) | 0X10;
    }
    else{
      reg_SQ_OFFSET_LANE_4_0 = ((VAR_OFST2 - VAR_OFST1) & 0XF);
    }
  }
