// Author: fei 2020-08-25
// Auto generated by IPDOC
  #include "common.h"
  #ifdef USE_BANKING
  #pragma codeseg BANK1
  #pragma constseg BANK1
  #endif
  void pll_vdd_freq_ts(void) BANKING_CTRL {
    reg_PLL_TS_LCPLL_DCC_EN_LANE = 1;
    reg_PLL_TS_LCDIV1P5_DCC_EN_LANE = 1;
    reg_PLL_TS_VDDA_CAL_EN_LANE = 1;
    reg_PLL_TS_VDDR_SEL_LANE_3_0 = 0XF;
    reg_PLL_TS_DCC_CAL_BYPASS_EN_LANE = 1;
    reg_PLL_TS_DIV_DCC_CAL_BYPASS_EN_LANE = 1;
    reg_PLL_TS_VDDA_PFD_CAL_BYPASS_EN_LANE = 1;
    reg_PLL_DCC_VDD_TS_TOP_START_LANE = 0;
    reg_PLL_DCC_VDD_TS_TOP_START_LANE = 1;
    delay(Tus);
    while(reg_PLL_DCC_VDD_TS_TOP_DONE_LANE == 0){
    }
    reg_PLL_DCC_VDD_TS_TOP_START_LANE = 0;
    if(reg_PLL_TS_VDDA_FBDIV_CAL_TIMEOUT_RD_LANE || reg_PLL_TS_VDDA_INTP_CAL_TIMEOUT_RD_LANE == 1){
      lnx_TX_PLLVDDA_CAL_PASS_LANE = 0;
    }
    else{
      lnx_TX_PLLVDDA_CAL_PASS_LANE = 1;
    }
    reg_PLL_TS_DCC_CAL_BYPASS_EN_LANE = 0;
    reg_PLL_TS_DIV_DCC_CAL_BYPASS_EN_LANE = 0;
    reg_PLL_TS_VDDA_PFD_CAL_BYPASS_EN_LANE = 0;
    reg_PLL_TS_LCPLL_DCC_EN_LANE = 0;
    reg_PLL_TS_LCDIV1P5_DCC_EN_LANE = 0;
    reg_PLL_TS_VDDA_CAL_EN_LANE = 0;
    reg_PLL_TS_VDDA_FBDIV_CAL_RESULT_EXT_LANE_3_0 = reg_PLL_TS_VDDA_FBDIV_CAL_RESULT_RD_LANE_3_0;
    reg_PLL_TS_VDDA_INTP_CAL_RESULT_EXT_LANE_3_0 = reg_PLL_TS_VDDA_INTP_CAL_RESULT_RD_LANE_3_0;
  }
