// Author: fei 2020-08-25
// Auto generated by IPDOC
  #include "common.h"
  #ifdef USE_BANKING
  #pragma codeseg BANK1
  #pragma constseg BANK1
  #endif
  void pll_dcc_vdd_rs(void) BANKING_CTRL {
    reg_PLL_RS_LCPLL_DCC_EN_LANE = 1;
    reg_PLL_RS_LCDIV1P5_DCC_EN_LANE = 1;
    if(reg_PLL_RS_LCPLL_POSTDIV_EN_LANE == 0){
      reg_PLL_RS_LCPLL_DCC_SEN_POINT_SEL_LANE = 1;
      reg_PLL_RS_DCC_CAL_BYPASS_EN_LANE = 0;
      reg_PLL_RS_DIV_DCC_CAL_BYPASS_EN_LANE = 1;
      reg_PLL_RS_VDDA_FBDIV_CAL_BYPASS_EN_LANE = 1;
      reg_PLL_RS_VDDA_INTP_CAL_BYPASS_EN_LANE
 = 1;
      reg_PLL_RS_VDDA_PFD_CAL_BYPASS_EN_LANE = 1;
      reg_PLL_DCC_VDD_RS_TOP_START_LANE = 0;
      reg_PLL_DCC_VDD_RS_TOP_START_LANE = 1;
      delay(Tus);
      while(reg_PLL_DCC_VDD_RS_TOP_DONE_LANE == 0){
      }
      reg_PLL_DCC_VDD_RS_TOP_START_LANE = 0;
      if(reg_PLL_RS_DCC_CAL_TIMEOUT_RD_LANE == 1){
        lnx_RX_PLLDCC_CAL_PASS_LANE = 0;
      }
      else{
        lnx_RX_PLLDCC_CAL_PASS_LANE = 1;
      }
      reg_PLL_RS_DCC_CAL_RESULT_EXT_LANE_6_0 = reg_PLL_RS_DCC_CAL_RESULT_RD_LANE_6_0;
      reg_PLL_RS_VDDA_FBDIV_CAL_BYPASS_EN_LANE = 0;
      reg_PLL_RS_VDDA_INTP_CAL_BYPASS_EN_LANE = 0;
      reg_PLL_RS_VDDA_PFD_CAL_BYPASS_EN_LANE = 0;
    }
    else{
      if(reg_PLL_RS_LCPLL_POSTDIV_1P5OR2_EN_LANE == 1){
        reg_PLL_RS_LCPLL_DIV2_1P5_CLKIN_DCC_SEL_LANE = 0;
        reg_PLL_RS_LCPLL_DCC_SEN_POINT_SEL_LANE = 0;
        reg_PLL_RS_DCC_CAL_BYPASS_EN_LANE = 0;
        reg_PLL_RS_DIV_DCC_CAL_BYPASS_EN_LANE = 0;
        reg_PLL_RS_VDDA_FBDIV_CAL_BYPASS_EN_LANE = 1;
        reg_PLL_RS_VDDA_INTP_CAL_BYPASS_EN_LANE = 1;
        reg_PLL_RS_VDDA_PFD_CAL_BYPASS_EN_LANE = 1;
        reg_PLL_DCC_VDD_RS_TOP_START_LANE = 0;
        reg_PLL_DCC_VDD_RS_TOP_START_LANE = 1;
        delay(Tus);
        while(reg_PLL_DCC_VDD_RS_TOP_DONE_LANE == 0){
        }
        reg_PLL_DCC_VDD_RS_TOP_START_LANE = 0;
        if(reg_PLL_RS_DCC_CAL_TIMEOUT_RD_LANE || reg_PLL_RS_DIV_DCC_CAL_TIMEOUT_RD_LANE == 1){
          lnx_RX_PLLDCC_CAL_PASS_LANE = 0;
        }
        else{
          lnx_RX_PLLDCC_CAL_PASS_LANE = 1;
        }
        reg_PLL_RS_DIV_DCC_CAL_RESULT_EXT_LANE_5_0 = reg_PLL_RS_DIV_DCC_CAL_RESULT_RD_LANE_5_0;
        reg_PLL_RS_VDDA_FBDIV_CAL_BYPASS_EN_LANE = 0;
        reg_PLL_RS_VDDA_INTP_CAL_BYPASS_EN_LANE = 0;
        reg_PLL_RS_VDDA_PFD_CAL_BYPASS_EN_LANE = 0;
      }
      else{
        reg_PLL_RS_LCPLL_DIV2_1P5_CLKIN_DCC_SEL_LANE = 1;
        reg_PLL_RS_LCPLL_DCC_SEN_POINT_SEL_LANE = 0;
        reg_PLL_RS_DCC_CAL_BYPASS_EN_LANE = 0;
        reg_PLL_RS_DIV_DCC_CAL_BYPASS_EN_LANE = 0;
        reg_PLL_RS_VDDA_FBDIV_CAL_BYPASS_EN_LANE = 1;
        reg_PLL_RS_VDDA_INTP_CAL_BYPASS_EN_LANE = 1;
        reg_PLL_RS_VDDA_PFD_CAL_BYPASS_EN_LANE = 1;
        reg_PLL_DCC_VDD_RS_TOP_START_LANE = 0;
        reg_PLL_DCC_VDD_RS_TOP_START_LANE = 1;
        delay(Tus);
        while(reg_PLL_DCC_VDD_RS_TOP_DONE_LANE == 0){
        }
        reg_PLL_DCC_VDD_RS_TOP_START_LANE = 0;
        if(reg_PLL_RS_DCC_CAL_TIMEOUT_RD_LANE || reg_PLL_RS_DIV_DCC_CAL_TIMEOUT_RD_LANE == 1){
          lnx_RX_PLLDCC_CAL_PASS_LANE = 0;
        }
        else{
          lnx_RX_PLLDCC_CAL_PASS_LANE = 1;
        }
        reg_PLL_RS_DIV_DCC_CAL_RESULT_EXT_LANE_5_0 = reg_PLL_RS_DIV_DCC_CAL_RESULT_RD_LANE_5_0;
        reg_PLL_RS_VDDA_FBDIV_CAL_BYPASS_EN_LANE = 0;
        reg_PLL_RS_VDDA_INTP_CAL_BYPASS_EN_LANE = 0;
        reg_PLL_RS_VDDA_PFD_CAL_BYPASS_EN_LANE = 0;
      }
    }
    reg_PLL_RS_VDDA_CAL_EN_LANE = 1;
    reg_PLL_RS_VDDR_SEL_LANE_3_0 = 0XF;
    reg_PLL_RS_DCC_CAL_BYPASS_EN_LANE = 1;
    reg_PLL_RS_DIV_DCC_CAL_BYPASS_EN_LANE = 1;
    reg_PLL_DCC_VDD_RS_TOP_START_LANE = 0;
    reg_PLL_DCC_VDD_RS_TOP_START_LANE = 1;
    delay(Tus);
    while(reg_PLL_DCC_VDD_RS_TOP_DONE_LANE == 0){
    }
    reg_PLL_DCC_VDD_RS_TOP_START_LANE = 0;
    if(reg_PLL_RS_VDDA_FBDIV_CAL_TIMEOUT_RD_LANE || reg_PLL_RS_VDDA_INTP_CAL_TIMEOUT_RD_LANE ||reg_PLL_RS_VDDA_PFD_CAL_TIMEOUT_RD_LANE == 1){
      lnx_RX_PLLVDDA_CAL_PASS_LANE = 0;
    }
    else{
      lnx_RX_PLLVDDA_CAL_PASS_LANE = 1;
    }
    reg_PLL_RS_DCC_CAL_BYPASS_EN_LANE = 0;
    reg_PLL_RS_DIV_DCC_CAL_BYPASS_EN_LANE = 0;
    reg_PLL_RS_VDDA_CAL_EN_LANE = 0;
    reg_PLL_RS_VDDA_FBDIV_CAL_RESULT_EXT_LANE_3_0 = reg_PLL_RS_VDDA_FBDIV_CAL_RESULT_RD_LANE_3_0;
    reg_PLL_RS_VDDA_INTP_CAL_RESULT_EXT_LANE_3_0 = reg_PLL_RS_VDDA_INTP_CAL_RESULT_RD_LANE_3_0;
    reg_PLL_RS_VDDA_PFD_CAL_RESULT_EXT_LANE_3_0 = reg_PLL_RS_VDDA_PFD_CAL_RESULT_RD_LANE_3_0;
  }
