#!/bin/sh
#soscmd co bintbls/*/*
#../../bin/gen_rtl/SpeedTable/MCU_PHY/gen_spdtbl_dev.pl -pll0 pllspeed_PI0.txt -pll1 pllspeed_PI1.txt -rpll0 ringpllspeed_PI0.txt -rpll1 ringpllspeed_PI1.txt -tx txspeed.txt -rx rxspeed.txt -cmn phy_mode_cmn.txt -lane phy_mode_lane.txt -hex -mode SERDES -gen 11 -ref_sel 7

#../../bin/gen_rtl/SpeedTable/MCU_PHY/gen_spdtbl_dev.pl -pll0 pllspeed_PI0.txt -pll1 pllspeed_PI1.txt -rpll0 ringpllspeed_PI0.txt -rpll1 ringpllspeed_PI1.txt -tx txspeed.txt -rx rxspeed.txt -cmn phy_mode_cmn.txt -lane phy_mode_lane.txt -match lane_num=4 -size 128 -hex -lc_size 28 -ring_size 32 -gen_size 80 -lane_start 6564 -cmn_start e5c0 -combine_serdes_gen

#../../bin/gen_rtl/SpeedTable/MCU_PHY/gen_spdtbl_dev.pl -pll0 pllspeed_PI0.txt -pll1 pllspeed_PI1.txt -rpll0 ringpllspeed_PI0.txt -rpll1 ringpllspeed_PI1.txt -tx txspeed.txt -rx rxspeed.txt -cmn phy_mode_cmn.txt -lane phy_mode_lane.txt -match lane_num=4 -size 128 -hex -lc_size 32 -ring_size 36 -gen_size 80 -lane_start 6564 -cmn_start e5c0 -combine_serdes_gen 0 1 2 4 7 10 13 14 16, 0 1 4 7 -rpll_entry_num 4

#../../bin/gen_rtl/SpeedTable/MCU_PHY/gen_spdtbl_dev.pl -pll0 pllspeed_PI0.txt -pll1 pllspeed_PI1.txt -rpll0 ringpllspeed_PI0.txt -rpll1 ringpllspeed_PI1.txt -tx txspeed.txt -rx rxspeed.txt -cmn phy_mode_cmn.txt -lane phy_mode_lane.txt -match lane_num=4 -size 128 -hex -lc_size 32 -ring_size 36 -gen_size 80 -lane_start 65D4 -cmn_start e5c0 -combine_serdes_gen 0 1 2 4 7 10 13 14 16, 0 1 4 7 -rpll_entry_num 4

#../../bin/gen_rtl/SpeedTable/MCU_PHY/gen_spdtbl_dev.pl -pll0 pllspeed_PI1.txt -pll1 pllspeed_PI1.txt -tx txspeed.txt -rx rxspeed.txt -cmn phy_mode_cmn.txt -lane phy_mode_lane.txt -match lane_num=4 -size 128 -hex -lc_size 32 -gen_size 84 -combine_serdes_gen 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 -rpll_entry_num 4 -combine

#../../bin/gen_rtl/SpeedTable/MCU_PHY/gen_spdtbl_dev.pl -pll1 pllspeed_PI1.txt -tx txspeed.txt -rx rxspeed.txt -cmn phy_mode_cmn.txt -lane phy_mode_lane.txt -match lane_num=4 -size 128 -hex -lc_size 32 -gen_size 84 -combine_serdes_gen 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 -rpll_entry_num 4 -combine -verbose

../../bin/gen_rtl/SpeedTable/MCU_PHY/gen_spdtbl_dev.pl -pll1 pllspeed_PI1.txt -tx txspeed.txt -rx rxspeed.txt -cmn phy_mode_cmn.txt -lane phy_mode_lane.txt -match lane_num=4 -size 128 -hex -lc_size 32 -gen_size 68 -combine_serdes_gen 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 -rpll_entry_num 4 -combine -verbose


soscmd co ../phy_top/tb/incl/spd_tb_decoder.v
cp bintbls/spd_tb_decoder.v ../phy_top/tb/incl/spd_tb_decoder.v

soscmd co ../DOC/midas/reg.midas_xdat_spd_cmn
soscmd co ../DOC/midas/reg.midas_xdat_spd_lane
cp ./bintbls/reg.midas_xdat_spd_cmn ../DOC/midas/
cp ./bintbls/reg.midas_xdat_spd_lane ../DOC/midas/

cp -r bintbls ../firmware/

cp ./bintbls/spdtb_oft.h ../firmware/inc/

cp ./bintbls/spdtb_adr.h ../firmware/inc/

